"""initial_schema

Revision ID: ec6141f5fc09
Revises: 
Create Date: 2026-04-06 18:57:08.232753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6141f5fc09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.Enum('DOOR_STATION', 'HOME_STATION', 'GUARD_STATION', 'SIP_CLIENT', 'CAMERA', name='devicetype', native_enum=False), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('web_port', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sip_enabled', sa.Boolean(), nullable=False),
    sa.Column('sip_account', sa.String(length=128), nullable=True),
    sa.Column('sip_password', sa.String(length=128), nullable=True),
    sa.Column('sip_server', sa.String(length=255), nullable=True),
    sa.Column('sip_port', sa.Integer(), nullable=True),
    sa.Column('sip_proxy', sa.String(length=255), nullable=True),
    sa.Column('rtsp_enabled', sa.Boolean(), nullable=False),
    sa.Column('rtsp_url', sa.String(length=512), nullable=True),
    sa.Column('unlock_enabled', sa.Boolean(), nullable=False),
    sa.Column('unlock_method', sa.Enum('HTTP_GET', 'HTTP_POST', 'SIP_DTMF', 'NONE', name='unlockmethod', native_enum=False), nullable=False),
    sa.Column('unlock_url', sa.String(length=512), nullable=True),
    sa.Column('unlock_username', sa.String(length=128), nullable=True),
    sa.Column('unlock_password', sa.String(length=128), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('DEVICE_CREATED', 'DEVICE_UPDATED', 'DEVICE_DELETED', 'UNLOCK_TEST', 'CONNECTION_TEST', 'LOGIN', 'RULE_CREATED', 'RULE_UPDATED', 'RULE_DELETED', name='activityaction', native_enum=False), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_id'), ['id'], unique=False)

    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('call_code', sa.String(length=64), nullable=False),
    sa.Column('source_device_id', sa.Integer(), nullable=True),
    sa.Column('target_device_id', sa.Integer(), nullable=True),
    sa.Column('target_sip_account', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routing_rules_call_code'), ['call_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_routing_rules_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routing_rules_id'))
        batch_op.drop_index(batch_op.f('ix_routing_rules_call_code'))

    op.drop_table('routing_rules')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_id'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_name'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    op.drop_table('devices')
    # ### end Alembic commands ###
